packages:
  - "packages/*"
  - "demos/*"

catalog:
  typescript: ^5.0.0
  vite: ^6.0.0
  "@cloudflare/vite-plugin": ^1.1.0
  "@cloudflare/workers-types": ^4.20241100.0
  wrangler: ^4.0.0
  "@types/node": ^24.0.0
